[tool.poetry]
name = "Python PlayGround"
version = "0.1.0"
description = "Random Python apps and functions"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2.3"
requests = "^2.28.2"



